plugins {
    id 'com.android.application'
}

android {
    namespace 'org.ippazio.privacylowvisionpdf'
    compileSdk 37

    defaultConfig {
        applicationId 'org.ippazio.privacylowvisionpdf'
        minSdk 28
        targetSdk 37
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.pdf:pdf-viewer-fragment:1.0.0-beta01'
}
